print("--------------------list data type-------")
my_list = ["saurav",10,10,20,40,30,10.5,"saurav123"]
print(my_list)
print(my_list)
print(my_list)
print(type(my_list))

print("--------------tuple data type----------")
my_tuple = ("saurav",10,20,40,30,10.5,"saurav123")
print(my_tuple)
print(my_tuple)
print(my_tuple)
print(my_tuple)
print(type(my_tuple))

print("-------------------range data type---------")
my_range =range(10)
print(list(my_range))
print(tuple(my_range))
print(type(my_range))
print(type(list(my_range)))
print(type(tuple(my_range)))